import { Task } from "@/hooks/type";

export const tasks: Task[] = [
  {
    id: "1",
    title: "Task 1",
    description: "Description for Task 1",
    assignee: "John Doe",
    team: "Team A",
    priority: "P1",
    status: "Pending",
    startDate: new Date("2024-01-05"),
  },
  {
    id: "2",
    title: "Task 2",
    description: "Description for Task 2",
    assignee: "Jane Smith",
    team: "Team B",
    priority: "P2",
    status: "In Progress",
    startDate: new Date("2024-01-05"),
    endDate: new Date(),
  },
  {
    id: "3",
    title: "Task 3",
    description: "Description for Task 3",
    assignee: "Emily Johnson",
    team: "Team C",
    priority: "P0",
    status: "Completed",
    startDate: new Date("2024-03-05"),
    endDate: new Date("2024-03-29"),
  },
  {
    id: "4",
    title: "Task 4",
    description: "Description for Task 4",
    assignee: "Michael Brown",
    team: "Team D",
    priority: "P1",
    status: "Completed",
    startDate: new Date("2024-02-05"),
    endDate: new Date("2024-04-10"),
  },

  {
    id: "9",
    title: "Task 9",
    description: "Description for Task 9",
    assignee: "Ava Thomas",
    team: "Team A",
    priority: "P1",
    status: "Deferred",
    startDate: new Date("2024-01-05"),
  },
  {
    id: "10",
    title: "Task 10",
    description: "Description for Task 10",
    assignee: "Noah Clark",
    team: "Team B",
    priority: "P2",
    status: "Deployed",
    startDate: new Date("2024-01-05"),
  },

  {
    id: "15",
    title: "Task 15",
    description: "Description for Task 15",
    assignee: "Mia Baker",
    team: "Team C",
    priority: "P0",
    status: "Deferred",
    startDate: new Date("2024-01-05"),
  },
  {
    id: "16",
    title: "Task 16",
    description: "Description for Task 16",
    assignee: "Jacob White",
    team: "Team D",
    priority: "P2",
    status: "Completed",
    startDate: new Date("2024-01-05"),
    endDate: new Date("2024-03-28"),
  },

  {
    id: "18",
    title: "Task 18",
    description: "Description for Task 18",
    assignee: "Matthew Lee",
    team: "Team B",
    priority: "P0",
    status: "Completed",
    startDate: new Date("2024-01-05"),
    endDate: new Date("2024-03-31"),
  },
];
